# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - linked-bdr

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.11' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          env

      - name: Install setup dependencies
        run: |
          . venv/bin/activate
          pip install -U pip && pip install -r requirements.txt

      - name: Install testing dependencies
        run: |
          . venv/bin/activate
          pip install -U pytest pytest-asyncio httpx
        

      - name: Run Tests
        run: |
          . venv/bin/activate
          env PYTHONPATH=. pytest test

      - name: Create and start deployment virtual environment
        run: |
          env -u VIRTUAL_ENV $pythonLocation/bin/python -m venv .python_packages
          . .python_packages/bin/activate

      - name: Install deployment dependencies
        run: |
          . .python_packages/bin/activate
          pip install -U pip && pip install -r requirements.txt

      - name: Zip artifact for deployment
        # Zip this including the .python_packages folder, but excluding the venv folder
        run: zip release.zip ./* .python_packages .funcignore -r -x "venv" -x "venv/*" -x ".git" -x "**/__pycache__/*" -x "*.pyc"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !.python_packages/
            !venv/
            !.git/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    #environment:
    #  name: 'Production'
    #  url: ${{ steps.deploy-to-function.outputs.app-url }}
    permissions:
      id-token: write #This is required for requesting the JWT


    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: | 
          unzip release.zip
          rm -f release.zip
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6F3015B1829246BF84A53F7173F64E93 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FA7267E17C06470D84CC47DC7C40E806 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ACD7A614EDBA4255B6CBED7625F73C4D }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        # On Consumption app on Linux, the only deployment option is WEBSITE_RUN_FROM_PACKAGE
        # When WEBSITE_RUN_FROM_PACKAGE is used, then oryx and scm-do-build cannot be enabled
        # Seo we must ensure all requirements are installed in the deployment virtual environment
        with:
          app-name: 'linked-bdr'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: false
          enable-oryx-build: false
          respect-funcignore: true
          #slot-name: 'Production'
